/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import javax.swing.*;

/**
 *
 * @author TOAN
 */
public class formMain extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public formMain() {
        initComponents();
        this.setExtendedState(formMain.MAXIMIZED_BOTH);
        this.setVisible(true);
        this.getJMenuBar().getMenu(5).getMenuComponent(1).setVisible(false);//Tắt Item Đổi mật khẩu
        this.getJMenuBar().getMenu(5).getMenuComponent(2).setVisible(false);// Tắt Item đăng xuất
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản Lý Nhà Trọ");

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1222, Short.MAX_VALUE)
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        menuBar.setForeground(new java.awt.Color(51, 255, 51));

        fileMenu.setIcon(new javax.swing.ImageIcon("D:\\workspace\\DoAnJava\\src\\main\\java\\pic\\uer32.png")); // NOI18N
        fileMenu.setMnemonic('k');
        fileMenu.setText("Khách Thuê");
        fileMenu.setToolTipText("");
        fileMenu.setEnabled(false);
        fileMenu.setMinimumSize(new java.awt.Dimension(114, 38));
        fileMenu.setPreferredSize(new java.awt.Dimension(114, 38));

        openMenuItem.setIcon(new javax.swing.ImageIcon("D:\\learn\\java\\DoAnJava\\src\\main\\java\\pic\\user_female_info.png")); // NOI18N
        openMenuItem.setMnemonic('K');
        openMenuItem.setText("Thông tin khách thuê");
        openMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(openMenuItem);

        menuBar.add(fileMenu);

        jMenu2.setIcon(new javax.swing.ImageIcon("D:\\learn\\java\\DoAnJava\\src\\main\\java\\pic\\motel.png")); // NOI18N
        jMenu2.setText("Phòng trọ");
        jMenu2.setEnabled(false);

        jMenuItem2.setIcon(new javax.swing.ImageIcon("D:\\learn\\java\\DoAnJava\\src\\main\\java\\pic\\home.png")); // NOI18N
        jMenuItem2.setText("Thông tin phòng trọ");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem3.setIcon(new javax.swing.ImageIcon("D:\\learn\\java\\DoAnJava\\src\\main\\java\\pic\\contract.png")); // NOI18N
        jMenuItem3.setText("Đăng ký phòng");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        menuBar.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon("D:\\learn\\java\\DoAnJava\\src\\main\\java\\pic\\e24f1be346a.png")); // NOI18N
        jMenu3.setText("Hóa Đơn");
        jMenu3.setEnabled(false);

        jMenuItem4.setIcon(new javax.swing.ImageIcon("D:\\learn\\java\\DoAnJava\\src\\main\\java\\pic\\information.png")); // NOI18N
        jMenuItem4.setText("Thông tin hóa đơn");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        menuBar.add(jMenu3);

        jMenu4.setIcon(new javax.swing.ImageIcon("D:\\learn\\java\\DoAnJava\\src\\main\\java\\pic\\order-1.png")); // NOI18N
        jMenu4.setText("Bảng Giá");
        jMenu4.setEnabled(false);

        jMenuItem5.setIcon(new javax.swing.ImageIcon("D:\\learn\\java\\DoAnJava\\src\\main\\java\\pic\\Home_1.png")); // NOI18N
        jMenuItem5.setText("Bảng giá phòng trọ");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem5);

        jMenuItem6.setIcon(new javax.swing.ImageIcon("D:\\learn\\java\\DoAnJava\\src\\main\\java\\pic\\30e9d39543d14e5821889fda236fad5d.png")); // NOI18N
        jMenuItem6.setText("Bảng giá dịch vụ");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem6);

        menuBar.add(jMenu4);

        jMenu5.setIcon(new javax.swing.ImageIcon("D:\\learn\\java\\DoAnJava\\src\\main\\java\\pic\\kchart.png")); // NOI18N
        jMenu5.setText("Thống Kê");
        jMenu5.setEnabled(false);

        jMenuItem7.setIcon(new javax.swing.ImageIcon("D:\\learn\\java\\DoAnJava\\src\\main\\java\\pic\\1368245115_total_plan_cost.png")); // NOI18N
        jMenuItem7.setText("Thống kê hóa đơn");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem7);

        menuBar.add(jMenu5);

        jMenu6.setIcon(new javax.swing.ImageIcon("D:\\learn\\java\\DoAnJava\\src\\main\\java\\pic\\icon-ols.png")); // NOI18N
        jMenu6.setText("Tài Khoản");

        jMenuItem8.setIcon(new javax.swing.ImageIcon("D:\\learn\\java\\DoAnJava\\src\\main\\java\\pic\\Login.png")); // NOI18N
        jMenuItem8.setText("Đăng Nhập");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem8);

        jMenuItem9.setIcon(new javax.swing.ImageIcon("D:\\learn\\java\\DoAnJava\\src\\main\\java\\pic\\[assword.png")); // NOI18N
        jMenuItem9.setText("Đổi mật khẩu");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem9);

        jMenuItem10.setIcon(new javax.swing.ImageIcon("D:\\learn\\java\\DoAnJava\\src\\main\\java\\pic\\logout.png")); // NOI18N
        jMenuItem10.setText("Đăng xuất");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem10);

        jMenuItem11.setIcon(new javax.swing.ImageIcon("D:\\learn\\java\\DoAnJava\\src\\main\\java\\pic\\exit.png")); // NOI18N
        jMenuItem11.setText("Thoát");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem11);

        menuBar.add(jMenu6);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void openMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openMenuItemActionPerformed
        // TODO add your handling code here:
        for(JInternalFrame f:desktopPane.getAllFrames())//Lặp tất cả các JInternal Frame trong desktop Pane
        if(f.getTitle().equals("Quản lý khách thuê phòng trọ"))//Nếu như có form nào trùng tên với form đang được bật
            return;
        //Nếu như form đó chưa được mở
        formKhachThue f = new formKhachThue();//Tạo mới
        desktopPane.add(f);
        f.setVisible(true);
    }//GEN-LAST:event_openMenuItemActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        for(JInternalFrame f:desktopPane.getAllFrames())
            if(f.getTitle().equals("Thông tin phòng trọ"))
                return;
        formPhongTro f = new formPhongTro();
        desktopPane.add(f);
        f.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        for(JInternalFrame f:desktopPane.getAllFrames())
            if(f.getTitle().equals("Đăng ký phòng"))
                return;
        formDangKyPhong f = new formDangKyPhong();
        desktopPane.add(f);
        f.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        for(JInternalFrame f:desktopPane.getAllFrames())
            if(f.getTitle().equals("Hóa đơn dịch vụ"))
                return;
        formHoaDonDichVu f = new formHoaDonDichVu();
        desktopPane.add(f);
        f.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        for(JInternalFrame f:desktopPane.getAllFrames())
            if(f.getTitle().equals("Bảng giá phòng trọ"))
                return;
        formBangGiaPhongTro f = new formBangGiaPhongTro();
        desktopPane.add(f);
        f.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        for(JInternalFrame f:desktopPane.getAllFrames())
            if(f.getTitle().equals("Thông tin dịch vụ"))
                return;
        formBangGiaDichVu f = new formBangGiaDichVu();
        desktopPane.add(f);
        f.setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        for(JInternalFrame f:desktopPane.getAllFrames())
            if(f.getTitle().equals("Thống kê hóa đơn"))
                return;
        formThongKe f = new formThongKe();
        desktopPane.add(f);
        f.setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        for(JInternalFrame f:desktopPane.getAllFrames())//Lặp tất cả các JInternal Frame trong desktop Pane
        if(f.getTitle().equals("Đăng nhập"))//Nếu như có form nào trùng tên với form đang được bật
        return;
        //Nếu như form đó chưa được mở
        formDangNhap f = new formDangNhap();//Tạo mới
        desktopPane.add(f);
        f.setVisible(true);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
        for(JInternalFrame f:desktopPane.getAllFrames())
            if(f.getTitle().equals("Đổi mật khẩu"))
                return;
        formDoiMatKhau f = new formDoiMatKhau();
        desktopPane.add(f);
        f.setVisible(true);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
        this.getJMenuBar().getMenu(0).setEnabled(false);
        this.getJMenuBar().getMenu(1).setEnabled(false);
        this.getJMenuBar().getMenu(2).setEnabled(false);
        this.getJMenuBar().getMenu(3).setEnabled(false);
        this.getJMenuBar().getMenu(4).setEnabled(false);
        this.getJMenuBar().getMenu(5).getMenuComponent(0).setVisible(true);//Hiện item Đăng nhập
        this.getJMenuBar().getMenu(5).getMenuComponent(1).setVisible(false);//tắt Item Đổi mật khẩu
        this.getJMenuBar().getMenu(5).getMenuComponent(2).setVisible(false);//tắt Item đăng xuất
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:
        int reply = JOptionPane.showConfirmDialog(null, "Bạn chắc chắn muốn thoát?", "Thông báo", JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) 
        {
          System.exit(0);
        }
        else 
        {
           return;           
        }
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem openMenuItem;
    // End of variables declaration//GEN-END:variables
}
