/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import BLL.BangGiaDichVuBLL;
import DTO.BangGiaDichVuDTO;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author TOAN
 */
public class formBangGiaDichVu extends javax.swing.JInternalFrame {

    /**
     * Creates new form formBangGiaDichVu
     */
    loadTable loadTbl = new loadTable();
    BangGiaDichVuBLL bangGiaBLL = new BangGiaDichVuBLL();
    
    
    public formBangGiaDichVu() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize(); //Lấy độ dài màn hình
        
        int w=this.getSize().width;
        int h=this.getSize().height;
        int x=(dim.width-w)/2;
        int y=(dim.height-h)/2;
        this.setLocation(x, y);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtGiaTien = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDichVu = new javax.swing.JTable();
        cbbMaLoaiDichVu = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnThem = new javax.swing.JButton();
        txtQuyCach = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnSua = new javax.swing.JButton();
        btnThemMoi = new javax.swing.JButton();
        txtMaDichVu = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnThoat = new javax.swing.JButton();
        btnCapNhat = new javax.swing.JButton();
        txtTenDichVu = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnXoa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Thông tin dịch vụ");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        txtGiaTien.setEnabled(false);
        txtGiaTien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGiaTienActionPerformed(evt);
            }
        });

        tblDichVu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblDichVu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDichVuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDichVu);

        cbbMaLoaiDichVu.setEnabled(false);

        jLabel4.setText("Giá Tiền");

        jLabel5.setText("Mã Loại Dịch Vụ");

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        txtQuyCach.setEnabled(false);

        jLabel6.setText("Quy Cách");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Thông Tin Dịch Vụ");

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnThemMoi.setText("Thêm Mới");
        btnThemMoi.setEnabled(false);
        btnThemMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemMoiActionPerformed(evt);
            }
        });

        txtMaDichVu.setEnabled(false);

        jLabel2.setText("Mã Dịch Vụ");

        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        btnCapNhat.setText("Cập Nhật");
        btnCapNhat.setEnabled(false);
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });

        txtTenDichVu.setEnabled(false);

        jLabel3.setText("Tên Dịch Vụ");

        btnXoa.setText("Xóa");
        btnXoa.setEnabled(false);
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jLabel1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnThem)
                            .addGap(18, 18, 18)
                            .addComponent(btnSua)
                            .addGap(18, 18, 18)
                            .addComponent(btnXoa)
                            .addGap(23, 23, 23)
                            .addComponent(btnThoat))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGap(30, 30, 30)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtMaDichVu, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtTenDichVu)
                                    .addComponent(txtGiaTien, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(44, 44, 44)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel6))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtQuyCach, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cbbMaLoaiDichVu, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnThemMoi)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnCapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbbMaLoaiDichVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaDichVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(txtTenDichVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtQuyCach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtGiaTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnThemMoi)
                                .addComponent(btnCapNhat))))
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnSua)
                    .addComponent(btnThoat)
                    .addComponent(btnXoa))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtGiaTienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGiaTienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGiaTienActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnThoatActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        txtMaDichVu.setEnabled(true);
        txtTenDichVu.setEnabled(true);
        txtGiaTien.setEnabled(true);
        txtQuyCach.setEnabled(true);
        btnThemMoi.setEnabled(true);
        btnCapNhat.setEnabled(false);
        cbbMaLoaiDichVu.getItemAt(0);
        cbbMaLoaiDichVu.setEnabled(true);
        txtMaDichVu.setText("");
        txtTenDichVu.setText("");
        txtQuyCach.setText("");
        txtGiaTien.setText("");
        cbbMaLoaiDichVu.getItemAt(0);
    }//GEN-LAST:event_btnThemActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        try {
            loadTbl.loadJTable(bangGiaBLL.LoadThongTinDichVu(), tblDichVu);
            loadTbl.loadJcombobox(bangGiaBLL.LoadMaLoaiDichVu(), cbbMaLoaiDichVu, "MaLoaiDichVu");
        } catch (Exception ex) {
            Logger.getLogger(formBangGiaDichVu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formInternalFrameOpened

    private void btnThemMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemMoiActionPerformed
        // TODO add your handling code here:
        if(txtMaDichVu.getText().equals("")|| txtTenDichVu.getText().equals("") || txtGiaTien.getText().equals("") || txtQuyCach.getText().equals("") ) {
            JOptionPane.showMessageDialog(rootPane, "Thông tin không được để trống");
        } else {
            BangGiaDichVuDTO bangGiaDichVuDTO = new BangGiaDichVuDTO();
            bangGiaDichVuDTO.setMaDichVu(txtMaDichVu.getText());
            bangGiaDichVuDTO.setTenDichVu(txtTenDichVu.getText());
            bangGiaDichVuDTO.setGiaTien(Integer.parseInt(txtGiaTien.getText()));
            bangGiaDichVuDTO.setMaLoaiDichVu(cbbMaLoaiDichVu.getSelectedItem().toString());
            bangGiaDichVuDTO.setQuyCach(txtQuyCach.getText());
            try {
                if(bangGiaBLL.ThemDichVu(bangGiaDichVuDTO) > 0) {
                    JOptionPane.showMessageDialog(rootPane, "Thêm thành công");
                    loadTbl.loadJTable(bangGiaBLL.LoadThongTinDichVu(), tblDichVu);
                    txtMaDichVu.setText("");
                    txtTenDichVu.setText("");
                    txtQuyCach.setText("");
                    txtGiaTien.setText("");
                    cbbMaLoaiDichVu.getItemAt(0);
                    btnCapNhat.setEnabled(false);
                    btnThemMoi.setEnabled(false);
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Thêm thất  bại");
                }
            } catch (Exception ex) {
                Logger.getLogger(formBangGiaDichVu.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnThemMoiActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        btnThemMoi.setEnabled(false);
        btnCapNhat.setEnabled(true);
        txtMaDichVu.setEnabled(false);
        txtTenDichVu.setEnabled(true);
        txtGiaTien.setEnabled(true);
        txtQuyCach.setEnabled(true);
        cbbMaLoaiDichVu.setEnabled(false);
        //Lấy index của bảng DIchVu khi click chuột vào
        int index=tblDichVu.getSelectedRow();
        //lấy giá tiền
        txtGiaTien.setText(String.valueOf(tblDichVu.getValueAt(index,2)).replaceAll(",",""));
    }//GEN-LAST:event_btnSuaActionPerformed

    private void tblDichVuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDichVuMouseClicked
        // TODO add your handling code here:
        txtMaDichVu.setEnabled(false);
        txtTenDichVu.setEnabled(false);
        txtGiaTien.setEnabled(false);
        txtQuyCach.setEnabled(false);
        cbbMaLoaiDichVu.setEnabled(false);
        btnXoa.setEnabled(true);
        int index=tblDichVu.getSelectedRow();
        txtMaDichVu.setText((String) tblDichVu.getValueAt(index,0));
        txtTenDichVu.setText((String) tblDichVu.getValueAt(index,1));
        txtGiaTien.setText(String.valueOf(tblDichVu.getValueAt(index,2)).replaceAll(",",""));
        txtQuyCach.setText((String) tblDichVu.getValueAt(index,4));
        cbbMaLoaiDichVu.setSelectedItem(tblDichVu.getValueAt(index, 3));
    }//GEN-LAST:event_tblDichVuMouseClicked

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        // TODO add your handling code here:
        if(txtMaDichVu.getText().equals("")|| txtTenDichVu.getText().equals("") || txtGiaTien.getText().equals("") || txtQuyCach.getText().equals("") ){
            JOptionPane.showMessageDialog(rootPane, "Thông tin nhập vào không được để trống");
        }
        else {
            BangGiaDichVuDTO bangGiaDichVuDTO = new BangGiaDichVuDTO();
            bangGiaDichVuDTO.setMaDichVu(txtMaDichVu.getText());
            bangGiaDichVuDTO.setTenDichVu(txtTenDichVu.getText());
            bangGiaDichVuDTO.setGiaTien(Integer.parseInt(txtGiaTien.getText()));
            bangGiaDichVuDTO.setMaLoaiDichVu(cbbMaLoaiDichVu.getSelectedItem().toString());
            bangGiaDichVuDTO.setQuyCach(txtQuyCach.getText());
            try{
                if(bangGiaBLL.SuaDichVu(bangGiaDichVuDTO) > 0) {
                    JOptionPane.showMessageDialog(rootPane, "Cập nhật thành công");
                    loadTbl.loadJTable(bangGiaBLL.LoadThongTinDichVu(), tblDichVu);
                    txtMaDichVu.setText("");
                    txtTenDichVu.setText("");
                    txtQuyCach.setText("");
                    txtGiaTien.setText("");
                    cbbMaLoaiDichVu.getItemAt(0);
                    btnCapNhat.setEnabled(false);
                    btnThemMoi.setEnabled(false);
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Cập nhật thất  bại");
                } 
            }catch (Exception ex) {
                Logger.getLogger(formBangGiaDichVu.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        String maDichVu = txtMaDichVu.getText();
        String tenDichVu = txtTenDichVu.getText();
        int thongBao = JOptionPane.showConfirmDialog(rootPane, "Bạn có muốn xóa dịch vụ có Mã dịch vụ: " +maDichVu+ " ,Tên dịch vụ: " + tenDichVu + " ?", "Thông báo" ,JOptionPane.YES_NO_OPTION);
        if(thongBao == JOptionPane.YES_OPTION) {
            BangGiaDichVuDTO bangGiaDichVuDTO = new BangGiaDichVuDTO();
            bangGiaDichVuDTO.setMaDichVu(maDichVu);
            if(bangGiaBLL.XoaDichVu(bangGiaDichVuDTO) > 0) {
                try {
                    JOptionPane.showMessageDialog(rootPane, "Xóa thành công thành công");
                    loadTbl.loadJTable(bangGiaBLL.LoadThongTinDichVu(), tblDichVu);
                    txtMaDichVu.setText("");
                    txtTenDichVu.setText("");
                    txtQuyCach.setText("");
                    txtGiaTien.setText("");
                    cbbMaLoaiDichVu.getItemAt(0);
                    btnCapNhat.setEnabled(false);
                    btnThemMoi.setEnabled(false);
                    btnXoa.setEnabled(false);
                } catch(Exception ex) {
                    Logger.getLogger(formBangGiaDichVu.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        
        
    }//GEN-LAST:event_btnXoaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formBangGiaDichVu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formBangGiaDichVu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formBangGiaDichVu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formBangGiaDichVu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formBangGiaDichVu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThemMoi;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbbMaLoaiDichVu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDichVu;
    private javax.swing.JTextField txtGiaTien;
    private javax.swing.JTextField txtMaDichVu;
    private javax.swing.JTextField txtQuyCach;
    private javax.swing.JTextField txtTenDichVu;
    // End of variables declaration//GEN-END:variables
}
