/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import DTO.KhachThueDTO;
import javax.swing.JOptionPane;
import GUI.loadTable;
import BLL.KhachThueBLL;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author TOAN
 */
public class formKhachThue extends javax.swing.JInternalFrame {

    /**
     * Creates new form formKhachThue
     */
    loadTable loadtbl = new loadTable();
    KhachThueBLL khachthue = new KhachThueBLL();
    public formKhachThue() {
        initComponents();
        try {
            loadtbl.loadJTable(khachthue.LoadKhachThue(), tblKhachThue);
            loadtbl.loadJTable(khachthue.LoadKhachThueDatPhong(), tblKhachThueDatPhong);
        } catch (Exception ex) {
            Logger.getLogger(formKhachThue.class.getName()).log(Level.SEVERE, null, ex);
        }
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize(); //Lấy độ dài màn hình
        
        int w=this.getSize().width;
        int h=this.getSize().height;
        int x=(dim.width-w)/2;
        int y=(dim.height-h)/2;
        this.setLocation(x, y);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKhachThue = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblKhachThueDatPhong = new javax.swing.JTable();
        gbThongTinKhach = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtMaKhach = new javax.swing.JTextField();
        txtTenKhach = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtQueQuan = new javax.swing.JTextField();
        txtNgheNghiep = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cbbPhai = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        txtCMND = new javax.swing.JTextField();
        btnCapNhat = new javax.swing.JButton();
        btnThemMoi = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtTaiKhoan = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtMatKhau = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        rbtnKhachKhongDatPhong = new javax.swing.JRadioButton();
        rbtnKhachCoDatPhong = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        txtTimKiem = new javax.swing.JTextField();
        btnTim = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        cbbLuaChon = new javax.swing.JComboBox<>();
        btnThoat = new javax.swing.JButton();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        setClosable(true);
        setTitle("Quản lý khách thuê phòng trọ");

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("QUẢN LÝ KHÁCH THUÊ PHÒNG");
        jLabel1.setMaximumSize(new java.awt.Dimension(321, 28));
        jLabel1.setMinimumSize(new java.awt.Dimension(321, 28));
        jLabel1.setPreferredSize(new java.awt.Dimension(321, 28));

        jPanel4.setBackground(new java.awt.Color(204, 255, 153));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin khách thuê"));
        jPanel4.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        jPanel4.setMinimumSize(new java.awt.Dimension(700, 150));
        jPanel4.setPreferredSize(new java.awt.Dimension(700, 150));

        tblKhachThue.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblKhachThue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKhachThueMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblKhachThue);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 719, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Chức năng"));
        jPanel3.setAlignmentX(0.0F);
        jPanel3.setAlignmentY(0.0F);
        jPanel3.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        jPanel3.setMinimumSize(new java.awt.Dimension(242, 41));

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.setEnabled(false);
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnSua.setText("Sửa");
        btnSua.setEnabled(false);
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnThem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnXoa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSua)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnXoa)
                    .addComponent(btnSua))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jButton3.setText("Load thông tin khách đặt phòng");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Danh sách khách đặt phòng"));
        jPanel6.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel6.setPreferredSize(new java.awt.Dimension(970, 130));

        tblKhachThueDatPhong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblKhachThueDatPhong.setOpaque(false);
        jScrollPane4.setViewportView(tblKhachThueDatPhong);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 954, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        gbThongTinKhach.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin khách"));
        gbThongTinKhach.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        gbThongTinKhach.setMinimumSize(new java.awt.Dimension(940, 72));
        gbThongTinKhach.setPreferredSize(new java.awt.Dimension(940, 72));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 255));
        jLabel2.setText("MÃ KHÁCH THUÊ");
        jLabel2.setMaximumSize(new java.awt.Dimension(83, 14));
        jLabel2.setMinimumSize(new java.awt.Dimension(83, 14));
        jLabel2.setPreferredSize(new java.awt.Dimension(83, 14));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 255));
        jLabel3.setText("TÊN KHÁCH THUÊ");

        txtMaKhach.setBackground(new java.awt.Color(242, 242, 242));
        txtMaKhach.setEnabled(false);
        txtMaKhach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaKhachActionPerformed(evt);
            }
        });

        txtTenKhach.setBackground(new java.awt.Color(242, 242, 242));
        txtTenKhach.setEnabled(false);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 255));
        jLabel4.setText("QUÊ QUÁN");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 255));
        jLabel5.setText("NGHỀ NGHIỆP");

        txtQueQuan.setBackground(new java.awt.Color(242, 242, 242));
        txtQueQuan.setEnabled(false);
        txtQueQuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQueQuanActionPerformed(evt);
            }
        });

        txtNgheNghiep.setBackground(new java.awt.Color(242, 242, 242));
        txtNgheNghiep.setEnabled(false);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 153, 255));
        jLabel6.setText("GIỚI TÍNH");

        cbbPhai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "nam", "nữ" }));
        cbbPhai.setEnabled(false);
        cbbPhai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbPhaiActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 153, 255));
        jLabel8.setText("CCCD/CMND");

        txtCMND.setBackground(new java.awt.Color(242, 242, 242));
        txtCMND.setEnabled(false);
        txtCMND.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCMNDActionPerformed(evt);
            }
        });

        btnCapNhat.setText("Cập nhật");
        btnCapNhat.setEnabled(false);
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });

        btnThemMoi.setText("Thêm mới");
        btnThemMoi.setEnabled(false);
        btnThemMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemMoiActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 153, 255));
        jLabel7.setText("TÀI KHOẢN");

        txtTaiKhoan.setEnabled(false);
        txtTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTaiKhoanActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 153, 255));
        jLabel10.setText("MẬT KHẨU");

        txtMatKhau.setEnabled(false);

        javax.swing.GroupLayout gbThongTinKhachLayout = new javax.swing.GroupLayout(gbThongTinKhach);
        gbThongTinKhach.setLayout(gbThongTinKhachLayout);
        gbThongTinKhachLayout.setHorizontalGroup(
            gbThongTinKhachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gbThongTinKhachLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(gbThongTinKhachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(gbThongTinKhachLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTenKhach))
                    .addGroup(gbThongTinKhachLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMaKhach, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(gbThongTinKhachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(gbThongTinKhachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtQueQuan, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addComponent(txtNgheNghiep))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(gbThongTinKhachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(gbThongTinKhachLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbbPhai, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCMND, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(gbThongTinKhachLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMatKhau)))
                .addGap(31, 31, 31)
                .addGroup(gbThongTinKhachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThemMoi))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        gbThongTinKhachLayout.setVerticalGroup(
            gbThongTinKhachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gbThongTinKhachLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(gbThongTinKhachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaKhach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtQueQuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(cbbPhai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtCMND, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCapNhat))
                .addGap(12, 12, 12)
                .addGroup(gbThongTinKhachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTenKhach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtNgheNghiep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(btnThemMoi)
                    .addComponent(txtMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Loại khách thuê"));

        rbtnKhachKhongDatPhong.setText("Khách không đặt phòng trước");
        rbtnKhachKhongDatPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnKhachKhongDatPhongActionPerformed(evt);
            }
        });

        rbtnKhachCoDatPhong.setText("Khách có đặt phòng trước");
        rbtnKhachCoDatPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnKhachCoDatPhongActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbtnKhachCoDatPhong)
                    .addComponent(rbtnKhachKhongDatPhong))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(rbtnKhachKhongDatPhong)
                .addGap(18, 18, 18)
                .addComponent(rbtnKhachCoDatPhong)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Tìm kiếm"));
        jPanel2.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(660, 52));

        txtTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimKiemActionPerformed(evt);
            }
        });

        btnTim.setText("Tìm");
        btnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimActionPerformed(evt);
            }
        });

        jLabel9.setText("Tìm kiếm theo: ");

        cbbLuaChon.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tên Khách", "Mã Khách", "Quê quán", "Nghề nghiệp" }));
        cbbLuaChon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbLuaChonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnTim)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(cbbLuaChon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTim)
                    .addComponent(jLabel9)
                    .addComponent(cbbLuaChon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 976, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnThoat))
                    .addComponent(gbThongTinKhach, javax.swing.GroupLayout.PREFERRED_SIZE, 1003, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 729, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(274, 274, 274)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gbThongTinKhach, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(btnThoat)))
                .addGap(49, 49, 49))
        );

        jLabel1.getAccessibleContext().setAccessibleParent(this);
        jPanel4.getAccessibleContext().setAccessibleParent(this);
        jPanel6.getAccessibleContext().setAccessibleParent(this);
        gbThongTinKhach.getAccessibleContext().setAccessibleParent(this);
        jPanel2.getAccessibleContext().setAccessibleParent(this);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMaKhachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaKhachActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaKhachActionPerformed

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        // TODO add your handling code here:
        if (txtTenKhach.getText().equals("") || txtCMND.getText().equals("") || txtNgheNghiep.getText().equals("") || txtQueQuan.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Thông tin nhập vào không được để trống");
        } else {
            //gán giá trị để sửa khách thuê
            KhachThueDTO khachThueDTO = new KhachThueDTO();
            khachThueDTO.setMaKhach(txtMaKhach.getText());
            khachThueDTO.setTenKhach(txtTenKhach.getText());
            khachThueDTO.setPhai(cbbPhai.getSelectedItem().toString());
            khachThueDTO.setCmnd(txtCMND.getText());
            khachThueDTO.setQueQuan(txtQueQuan.getText());
            khachThueDTO.setNgheNghiep(txtNgheNghiep.getText());
            khachThueDTO.setTaiKhoan(txtTaiKhoan.getText());
            
            if(khachthue.SuaKhachThue(khachThueDTO) > 0) {//Nếu sửa thành công
                try{
                    JOptionPane.showMessageDialog(rootPane, "Cập nhật thành công");
                    loadtbl.loadJTable(khachthue.LoadKhachThue(), tblKhachThue);
                    loadtbl.loadJTable(khachthue.LoadKhachThueDatPhong(), tblKhachThueDatPhong);
                } catch (Exception ex) {
                    Logger.getLogger(formKhachThue.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "Cập nhật thất bại");
            }
            txtMaKhach.setText("");
            txtTenKhach.setText("");
            txtCMND.setText("");
            txtTaiKhoan.setText("");
            txtQueQuan.setText("");
            txtNgheNghiep.setText("");
            //txtMaKhach.setText("");
            txtMaKhach.setEnabled(false);
            txtTenKhach.setEnabled(false);
            txtCMND.setEnabled(false);
            txtTaiKhoan.setEnabled(false);
            txtQueQuan.setEnabled(false);
            txtNgheNghiep.setEnabled(false);
            cbbPhai.setEnabled(false);
            btnCapNhat.setEnabled(false);
            btnXoa.setEnabled(false);
            btnSua.setEnabled(false);
        }
    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void txtQueQuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQueQuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQueQuanActionPerformed

    private void cbbPhaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbPhaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbPhaiActionPerformed

    private void txtTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimKiemActionPerformed

    private void cbbLuaChonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbLuaChonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbLuaChonActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        //Nếu như chưa có radioButton nào được chọn
        if (!rbtnKhachCoDatPhong.isSelected() && !rbtnKhachKhongDatPhong.isSelected()) {
            JOptionPane.showMessageDialog(rootPane, "Hãy chọn loại khách cần thêm ");
            return;
        }
        //ẩn hiện và gán giá trị rỗng cho các textfield
        txtTenKhach.setEnabled(true);
        txtMaKhach.setEnabled(true);
        txtCMND.setEnabled(true);
        txtQueQuan.setEnabled(true);
        txtNgheNghiep.setEnabled(true);
        cbbPhai.setEnabled(true);
        gbThongTinKhach.enable(true);
        btnCapNhat.setEnabled(false);
        btnThemMoi.setEnabled(true);
        txtMaKhach.setText("");
        txtTenKhach.setText("");
        cbbPhai.setSelectedIndex(0);
        txtCMND.setText("");
        txtNgheNghiep.setText("");
        txtQueQuan.setText("");
        txtTaiKhoan.setEnabled(true);
        txtMatKhau.setEnabled(true);

        
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimActionPerformed
        // TODO add your handling code here:
        try{
            KhachThueDTO khachThueDTO = new KhachThueDTO();
            switch (cbbLuaChon.getSelectedIndex()){
                case 0:
                        khachThueDTO.setTenKhach(txtTimKiem.getText());
                        loadtbl.loadJTable(khachthue.TimKhachThueTheoTen(khachThueDTO), tblKhachThue);
                        break;
                case 1:
                        khachThueDTO.setMaKhach(txtTimKiem.getText());
                        loadtbl.loadJTable(khachthue.TimKhachThueTheoMa(khachThueDTO), tblKhachThue);
                        break;
                case 2: 
                        khachThueDTO.setQueQuan(txtTimKiem.getText());
                        loadtbl.loadJTable(khachthue.TimKhachThueTheoQueQuan(khachThueDTO), tblKhachThue);
                        break;
                case 3:
                        khachThueDTO.setNgheNghiep(txtTimKiem.getText());
                        loadtbl.loadJTable(khachthue.TimKhachThueTheoNgheNghiep(khachThueDTO), tblKhachThue);
                        break;
            }
        } catch (Exception ex) {
            Logger.getLogger(formKhachThue.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnTimActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        String tenKhach = txtTenKhach.getText();
        String maKhach = txtMaKhach.getText();
        String cmnd = txtCMND.getText();
        int thongBao = JOptionPane.showConfirmDialog(rootPane,"Bạn muốn xóa khách "+ tenKhach + ". Có mã " + maKhach + ".", "Thông báo", JOptionPane.YES_NO_OPTION );
        if(thongBao == JOptionPane.YES_OPTION) {
            KhachThueDTO khachThueDTO = new KhachThueDTO();
            khachThueDTO.setMaKhach(maKhach); //Lấy giá trị mã khách
            khachThueDTO.setCmnd(cmnd);
            if(khachthue.XoaKhachThue(khachThueDTO) > 0){ //nếu xóa thành công
                try{
                  JOptionPane.showMessageDialog(rootPane, "Đã Xóa");
                  loadtbl.loadJTable(khachthue.LoadKhachThue(), tblKhachThue); //load lại bảng khách thuê
                  loadtbl.loadJTable(khachthue.LoadKhachThueDatPhong(), tblKhachThueDatPhong);
                } catch(Exception ex) {
                    Logger.getLogger(formKhachThue.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        
        
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        txtMaKhach.setEnabled(true);
        txtTenKhach.setEnabled(true);
        txtCMND.setEnabled(true);
        txtQueQuan.setEnabled(true);
        txtNgheNghiep.setEnabled(true);
        cbbPhai.setEnabled(true);
        gbThongTinKhach.setEnabled(true);
        btnCapNhat.setEnabled(true);
        txtTaiKhoan.setEnabled(true);
        
        int index = tblKhachThue.getSelectedRow();
        txtMaKhach.setText((String) tblKhachThue.getValueAt(index,0));
        txtTenKhach.setText((String) tblKhachThue.getValueAt(index, 1));
        String Phai = ((String) tblKhachThue.getValueAt(index, 2));
        if(Phai.equals("Nam")) 
            cbbPhai.setSelectedIndex(0);
        else
        cbbPhai.setSelectedIndex(1);
        txtCMND.setText((String) tblKhachThue.getValueAt(index, 3));
        txtQueQuan.setText((String) tblKhachThue.getValueAt(index, 4));
        txtNgheNghiep.setText((String) tblKhachThue.getValueAt(index, 5));
        
    }//GEN-LAST:event_btnSuaActionPerformed

    private void tblKhachThueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKhachThueMouseClicked
        // TODO add your handling code here:
        int index = tblKhachThue.getSelectedRow();
        txtMaKhach.setText((String) tblKhachThue.getValueAt(index,0));
        txtTenKhach.setText((String) tblKhachThue.getValueAt(index, 1));
        String Phai = ((String) tblKhachThue.getValueAt(index, 2));
        if(Phai.equals("Nam")) 
            cbbPhai.setSelectedIndex(0);
        else
            cbbPhai.setSelectedIndex(1);
        txtCMND.setText((String) tblKhachThue.getValueAt(index, 3));
        txtQueQuan.setText((String) tblKhachThue.getValueAt(index, 4));
        txtNgheNghiep.setText((String) tblKhachThue.getValueAt(index, 5));
        btnSua.setEnabled(true);
        btnXoa.setEnabled(true);
    }//GEN-LAST:event_tblKhachThueMouseClicked

    private void txtCMNDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCMNDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCMNDActionPerformed

    private void btnThemMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemMoiActionPerformed
        // TODO add your handling code here:
        if (txtMaKhach.getText().equals("") || txtTenKhach.getText().equals("") || txtCMND.getText().equals("") || txtNgheNghiep.getText().equals("") || txtQueQuan.getText().equals("")) {
            if(rbtnKhachCoDatPhong.isSelected() && txtMatKhau.getText().equals("")||txtTaiKhoan.getText().equals("")) {
                JOptionPane.showMessageDialog(rootPane, "Thông tin nhập vào không được để trống");
            return;
            } else {
                JOptionPane.showMessageDialog(rootPane, "Thông tin nhập vào không được để trống");
            }
        }
        
        KhachThueDTO khachThueDTO = new KhachThueDTO();
        khachThueDTO.setMaKhach(txtMaKhach.getText());
        khachThueDTO.setTenKhach(txtTenKhach.getText());
        khachThueDTO.setPhai(cbbPhai.getSelectedItem().toString());
        khachThueDTO.setQueQuan(txtQueQuan.getText());
        khachThueDTO.setNgheNghiep(txtNgheNghiep.getText());
        khachThueDTO.setCmnd(txtCMND.getText());
        khachThueDTO.setTaiKhoan(txtTaiKhoan.getText());
        khachThueDTO.setMatKhau(txtMatKhau.getText());

        if(rbtnKhachCoDatPhong.isSelected()) {
            System.out.println("hehe");
            if(khachthue.ThemKhachThueDatPhong(khachThueDTO) > 0) {
                try {
                    JOptionPane.showMessageDialog(rootPane,"Đã thêm khách thuê thành công");
                    //load lại các table và bỏ check các radiobutton
                    loadtbl.loadJTable(khachthue.LoadKhachThue(), tblKhachThue);
                    loadtbl.loadJTable(khachthue.LoadKhachThueDatPhong(), tblKhachThueDatPhong);
                    rbtnKhachCoDatPhong.setSelected(false);
                    rbtnKhachKhongDatPhong.setSelected(false);
                } catch (Exception ex) {
                    Logger.getLogger(formKhachThue.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "Thêm khách thuê thất bại");
            }
        }
        
        if(rbtnKhachKhongDatPhong.isSelected()) {
            System.out.println("huhu");
            if(khachthue.ThemKhachThueKhongDatPhong(khachThueDTO) > 0) {
                try {
                    JOptionPane.showMessageDialog(rootPane, "Thêm khách thuê thành công");
                    loadtbl.loadJTable(khachthue.LoadKhachThue(), tblKhachThue);
                    loadtbl.loadJTable(khachthue.LoadKhachThueDatPhong(), tblKhachThueDatPhong);
                    rbtnKhachCoDatPhong.setSelected(false);
                    rbtnKhachKhongDatPhong.setSelected(false);
                }   catch (Exception ex) {
                    Logger.getLogger(formKhachThue.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        txtMaKhach.setText("");
        txtTenKhach.setText("");
        txtCMND.setText("");
        txtTaiKhoan.setText("");
        txtQueQuan.setText("");
        txtNgheNghiep.setText("");
        txtMatKhau.setText("");
        //txtMaKhach.setText("");
        txtMaKhach.setEnabled(false);
        txtTenKhach.setEnabled(false);
        txtCMND.setEnabled(false);
        txtTaiKhoan.setEnabled(false);
        txtQueQuan.setEnabled(false);
        txtNgheNghiep.setEnabled(false);
        txtMatKhau.setEnabled(false);
        cbbPhai.setEnabled(false);
        btnThemMoi.setEnabled(false);
        
    }//GEN-LAST:event_btnThemMoiActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if (tblKhachThueDatPhong.getSelectedRow() == -1)//nếu như chưa chọn bất kì hàng nào
        {
            JOptionPane.showMessageDialog(rootPane, "Vui lòng chọn khách cần load thông tin");
            return;
        }
        int index = tblKhachThueDatPhong.getSelectedRow();//lấy index hàng được chọn
        //load thông tin lên các textfield và combobox khi chọn hàng
        txtCMND.setText((String) tblKhachThueDatPhong.getValueAt(index, 4));
        txtTenKhach.setText((String) tblKhachThueDatPhong.getValueAt(index, 2));
        txtQueQuan.setText((String) tblKhachThueDatPhong.getValueAt(index, 6));
        txtNgheNghiep.setText((String) tblKhachThueDatPhong.getValueAt(index, 5));
        cbbPhai.setSelectedItem((String) tblKhachThueDatPhong.getValueAt(index, 3));
        txtMaKhach.setText((String) tblKhachThueDatPhong.getValueAt(index, 1));
        txtTaiKhoan.setText((String) tblKhachThueDatPhong.getValueAt(index, 0));
    }//GEN-LAST:event_jButton3ActionPerformed

    private void rbtnKhachKhongDatPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnKhachKhongDatPhongActionPerformed
        // TODO add your handling code here:
        if(rbtnKhachKhongDatPhong.isSelected()) {
            rbtnKhachCoDatPhong.setSelected(false);
        }
    }//GEN-LAST:event_rbtnKhachKhongDatPhongActionPerformed

    private void rbtnKhachCoDatPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnKhachCoDatPhongActionPerformed
        // TODO add your handling code here:
        if(rbtnKhachCoDatPhong.isSelected()) {            
            rbtnKhachKhongDatPhong.setSelected(false);
        }
    }//GEN-LAST:event_rbtnKhachCoDatPhongActionPerformed

    private void txtTaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTaiKhoanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTaiKhoanActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnThoatActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formKhachThue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formKhachThue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formKhachThue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formKhachThue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formKhachThue().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThemMoi;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnTim;
    private javax.swing.JButton btnXoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbbLuaChon;
    private javax.swing.JComboBox<String> cbbPhai;
    private javax.swing.JPanel gbThongTinKhach;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JRadioButton rbtnKhachCoDatPhong;
    private javax.swing.JRadioButton rbtnKhachKhongDatPhong;
    private javax.swing.JTable tblKhachThue;
    private javax.swing.JTable tblKhachThueDatPhong;
    private javax.swing.JTextField txtCMND;
    private javax.swing.JTextField txtMaKhach;
    private javax.swing.JTextField txtMatKhau;
    private javax.swing.JTextField txtNgheNghiep;
    private javax.swing.JTextField txtQueQuan;
    private javax.swing.JTextField txtTaiKhoan;
    private javax.swing.JTextField txtTenKhach;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
